!!ExportedWorkflow
apiVersion: torq.io/v2alpha
kind: Workflow
id: 051d9e48-8ca5-45f8-a732-e5b704e1a9ab
name: Zoho Custom Step Testing
trigger:
  onDemandTrigger:
    parameterList:
      parameters: []
playbook:
  steps:
    - name: us-docker.pkg.dev/stackpulse/public/http/request:4.33.0
      id: send_an_http_request
      env:
        AUTHORIZATION: None
        HEADERS: '{"authorization":"Zoho-oauthtoken 1000.3d0a155402dbb59f776fd63adb1e67c0.a41ea557a6a8d7e402690098b2056f60s","orgid":"2389290"}'
        METHOD: GET
        URL: https://desk.zoho.com/api/v1/tickets/1892000000143237?include=contacts,products,assignee,departments,team
      uuid: 7cd7462c-4ecc-4a6d-bb42-d486ae1c1371
      pretty_name: Send an HTTP request
      options:
        executor:
          name: http_request_v_4_35_0
          env: {}
          sync: true
          disable: false
      manifestId: 7a86e1b9-edf7-5a09-a8be-149d431a01ee
      isPrivate: false
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
    - name: custom-step:1.0.0
      id: get_a_ticket
      env:
        ACCESS_TOKEN: ""
        INCLUDE_PARAMETERS: ""
        ORG_ID: ""
        TICKET_NUMBER: ""
      uuid: 003f37fb-9313-4355-aea5-e6978e3fe190
      pretty_name: Get a ticket
      options:
        executor:
          name: http_request_v_4_35_0
          env: {}
          sync: true
          disable: false
      documentationUrl: https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Getaticket
      manifestId: ac95306d-9e2c-49e2-9e1b-0deea76a9049
      isPrivate: true
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
    - name: us-docker.pkg.dev/stackpulse/public/http/request:4.33.0
      id: create_indicator
      env:
        AUTHORIZATION: Bearer
        BODY: |
          {
              "indicators": [
                  {
                      "action": "<INDICATOR_ACTION>",
                      "applied_globally": true,
                      "host_groups": [],
                      "platforms": <INDICATOR_PLATFORMS>,
                      "severity": "low",
                      "type": "sha256",
                      "value": "<INDICATOR_VALUE>"
                  }
              ]
          }
        CONTENT_TYPE: application/json
        HEADERS: ""
        METHOD: POST
        TIMEOUT: "30"
        TOKEN: ""
        URL: '{{ $.integrations.''<crowdstrike_token_integration>''.base_url }}/iocs/entities/indicators/v1'
      uuid: 0323b98f-3ad7-4cd3-b7b8-145b7336d533
      pretty_name: Create Indicator
      options:
        executor:
          name: http_request_v_4_35_0
          env: {}
          sync: true
          disable: false
      icon: https://cdn.torq.io/vendors/crowdstrike.svg
      manifestId: 7a86e1b9-edf7-5a09-a8be-149d431a01ee
      isPrivate: false
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
    - name: us-docker.pkg.dev/stackpulse/public/crowdstrike/remove-tags-from-a-case:1.0.0
      id: remove_tags_from_a_case
      env:
        CASE_ID: ""
        TAG: ""
      envFrom:
        integrationRef: crowdstrike_nfr
      uuid: dec90092-ca12-459e-97f2-733bdb53b68f
      pretty_name: Remove tags from a case
      options:
        executor:
          name: http_request_v_4_32_0
          env: {}
          sync: true
          disable: false
      manifestId: 4b6d4419-c14e-54ab-bb3e-1e43d3f1efd6
      isPrivate: false
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
    - name: us-docker.pkg.dev/stackpulse/public/utils/output_utils/set-variable:2.3.0
      id: set_variable
      env:
        DATA_TYPE: string
        VALUE_STRING: ""
        VARIABLE_NAME: ""
      uuid: 8b1069b7-6fcc-414f-8e8b-65fa43b6dca6
      pretty_name: Set Variable
      options:
        executor:
          name: utils_infrastructure_v_1_41_0
          env: {}
          sync: true
          disable: false
      manifestId: 7b868a61-a5f1-53a3-ad5a-7c115d591b2e
      isPrivate: false
      mock_output:
        enabled: false
      skip: false
      retry: {}
    - name: us-docker.pkg.dev/stackpulse/public/utils/output_utils/print:2.2.0
      id: print_a_message_to_stdout
      env:
        __TQ_FILE_ENV_PARSER__FILE_OR_STRING: plain-text
        FILE_OR_STRING: '{{ $.set_variable.step_status }}'
      uuid: 38ce9fe8-bd7f-4a3b-bb48-b3244b5f7c48
      pretty_name: Print a message to stdout
      options:
        executor:
          name: utils_infrastructure_v_1_41_0
          env: {}
          sync: true
          disable: false
      manifestId: e43d76f2-4382-5e23-a993-f15651735991
      isPrivate: false
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
  output_schema: '{}'
  section: Zoho
root: true
---
!!ExportedPrivateStep
basestepid: 7a86e1b9-edf7-5a09-a8be-149d431a01ee
vendor:
  id: ""
  icon: https://assets.torq.io/vendors/zoho.svg
  vendor: zoho
  name: Zoho
  is_private: false
name: Get a ticket
description: This API fetches a single ticket from your helpdesk.
documentationurl: https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Getaticket
runtime:
  image: us-docker.pkg.dev/stackpulse/public/http/request
  imageVersion: 4.33.0
  envs:
    - key: HEADERS
      value: |-
        {
          "authorization": "Zoho-oauthtoken {{ .ACCESS_TOKEN | jsonEscape }}",
          "orgid": "{{ .ORG_ID | jsonEscape }}"
        }
    - key: AUTHORIZATION
      value: None
    - key: URL
      value: https://desk.zoho.com/api/v1/tickets/{{ .TICKET_NUMBER | urlEnc }}?include={{ .INCLUDE_PARAMETERS | urlEnc }}
    - key: METHOD
      value: GET
    - key: BODY
      value: ""
    - key: CONTENT_TYPE
      value: application/json; charset=utf-8
    - key: PARSE_HJSON
      value: "true"
    - key: REQUIRED_VARIABLES
      value: '["TICKET_NUMBER","INCLUDE_PARAMETERS","ACCESS_TOKEN","ORG_ID"]'
    - key: FAIL_ON_NON_SUCCESS_RESPONSE
      value: "true"
    - key: GO_TEMPLATE_BODY_PARSING
      value: "true"
    - key: RESPONSE_API_OBJECT_ONLY
      value: "true"
envs:
  - name: TICKET_NUMBER
    description: This is a ticket number
    type: string
    required: true
    options: {}
  - name: INCLUDE_PARAMETERS
    type: string
    required: true
    options: {}
  - name: ACCESS_TOKEN
    type: string
    required: true
    options: {}
  - name: ORG_ID
    type: string
    required: true
    options: {}
outputs:
  - name: api_object
    type: json
integrations: []
basetype: 1
options:
  executor:
    name: http_request_v_4_35_0
    sync: true
  outputToFile: true
exportedstepid: ac95306d-9e2c-49e2-9e1b-0deea76a9049
rawmanifest:
  apiVersion: stackpulse.io/v1
  kind: Step
  metadata:
    name: Get a ticket
    imageName: custom-step
    description: This API fetches a single ticket from your helpdesk.
    type: custom
    vendor: zoho
    version: 1.0.0
    featureFlag: ""
    documentation_url: https://desk.zoho.com/DeskAPIDocument#Tickets#Tickets_Getaticket
    isPrivate: true
    privateStep:
      base: 1
  outputs:
    - name: api_object
      type: json
  envs:
    - name: TICKET_NUMBER
      description: This is a ticket number
      type: string
      required: true
      options: {}
    - name: INCLUDE_PARAMETERS
      type: string
      required: true
      options: {}
    - name: ACCESS_TOKEN
      type: string
      required: true
      options: {}
    - name: ORG_ID
      type: string
      required: true
      options: {}
  options:
    executor:
      name: http_request_v_4_35_0
      sync: true
    outputToFile: true
  http:
    imageName: us-docker.pkg.dev/stackpulse/public/http/request
    imageVersion: 4.33.0
    envs:
      AUTHORIZATION: None
      BODY: ""
      CONTENT_TYPE: application/json; charset=utf-8
      HEADERS: |-
        {
          "authorization": "Zoho-oauthtoken {{ .ACCESS_TOKEN | jsonEscape }}",
          "orgid": "{{ .ORG_ID | jsonEscape }}"
        }
      METHOD: GET
      PARSE_HJSON: "true"
      REQUIRED_VARIABLES: '["TICKET_NUMBER","INCLUDE_PARAMETERS","ACCESS_TOKEN","ORG_ID"]'
      URL: https://desk.zoho.com/api/v1/tickets/{{ .TICKET_NUMBER | urlEnc }}?include={{ .INCLUDE_PARAMETERS | urlEnc }}
  runtime:
    image: us-docker.pkg.dev/stackpulse/public/http/request
    imageVersion: 4.33.0
    envs:
      - key: HEADERS
        value: |-
          {
            "authorization": "Zoho-oauthtoken {{ .ACCESS_TOKEN | jsonEscape }}",
            "orgid": "{{ .ORG_ID | jsonEscape }}"
          }
      - key: AUTHORIZATION
        value: None
      - key: URL
        value: https://desk.zoho.com/api/v1/tickets/{{ .TICKET_NUMBER | urlEnc }}?include={{ .INCLUDE_PARAMETERS | urlEnc }}
      - key: METHOD
        value: GET
      - key: BODY
        value: ""
      - key: CONTENT_TYPE
        value: application/json; charset=utf-8
      - key: PARSE_HJSON
        value: "true"
      - key: REQUIRED_VARIABLES
        value: '["TICKET_NUMBER","INCLUDE_PARAMETERS","ACCESS_TOKEN","ORG_ID"]'
      - key: FAIL_ON_NON_SUCCESS_RESPONSE
        value: "true"
      - key: GO_TEMPLATE_BODY_PARSING
        value: "true"
      - key: RESPONSE_API_OBJECT_ONLY
        value: "true"
